### ISSUE TITLE
application.registry.lookup is not a function - Erroring on Ember 2.3.0

### ISSUE THREAD

**Issue by MorganIsBatman** [BryanCrotaz/ember-cli-browser-update#5]
I have this error occurring even though I can see it was remedied for Ember 2.0.

**Comment by plcarmel** [comment]
I had the same problem. It looks like there has been no new release in a while... So you have to download the source (github or otherwise) directly instead of using npm.

**Comment by BryanCrotaz** [comment]
published to npm
